#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
import tomllib
from datetime import datetime
from pathlib import Path

HEX = re.compile(r"^#[0-9A-Fa-f]{6}$")
THEME_KEYS = ("enableTerm", "enableHypr", "enableGtk", "enableQt")
WALL_UTILITY_REFS = {
    "surface_radius": ("shape", "radius_surface"),
    "panel_motion": ("motion", "panel_ms"),
    "orbit_motion": ("motion", "standard_ms"),
    "crossfade_motion": ("motion", "standard_ms"),
    "orbit_top_gap": ("spacing", "section"),
    "orbit_bottom_gap": ("spacing", "section"),
    "footer_gap": ("spacing", "compact"),
    "category_gap": ("spacing", "compact"),
}


def repo_root(value: str | None) -> Path:
    if value:
        return Path(value).expanduser().resolve()
    return Path(__file__).resolve().parents[1]


def resolve_wall_utility(data: dict) -> dict[str, int]:
    config = data.get("wall_utility")
    if not isinstance(config, dict):
        raise ValueError("missing [wall_utility] section")
    resolved: dict[str, int] = {}
    for name, (section, key) in WALL_UTILITY_REFS.items():
        reference = config.get(name)
        expected = f"{section}.{key}"
        if reference != expected:
            raise ValueError(f"invalid wall_utility.{name}: expected {expected!r}")
        value = data.get(section, {}).get(key)
        if not isinstance(value, int) or isinstance(value, bool) or value <= 0:
            raise ValueError(f"invalid wall_utility resolved value: {expected}")
        resolved[name] = value
    return resolved


def load_ui(repo: Path) -> dict:
    path = repo / "dotfiles/home/.config/cortetsu/ui.toml"
    with path.open("rb") as handle:
        data = tomllib.load(handle)
    if data.get("schema") != 1:
        raise ValueError("ui.toml schema must be 1")
    palette = data.get("palette", {})
    for name in ("sumi", "tetsu", "washi", "indigo", "vermillion", "muted"):
        value = palette.get(name)
        if not isinstance(value, str) or not HEX.fullmatch(value):
            raise ValueError(f"invalid palette.{name}: {value!r}")
    semantic = palette.get("semantic", {})
    for name in ("surface_high", "primary_container", "secondary", "secondary_container", "outline_variant", "scrim"):
        value = semantic.get(name)
        if not isinstance(value, str) or not HEX.fullmatch(value):
            raise ValueError(f"invalid palette.semantic.{name}: {value!r}")
    motion = data.get("motion", {})
    for name in ("instant_ms", "fast_ms", "standard_ms", "deliberate_ms"):
        if not isinstance(motion.get(name), int) or motion[name] <= 0:
            raise ValueError(f"invalid motion.{name}")
    if not isinstance(motion.get("hover_scale"), (int, float)) or motion["hover_scale"] <= 1:
        raise ValueError("invalid motion.hover_scale")
    resolve_wall_utility(data)
    return data


def rgb(value: str) -> tuple[int, int, int]:
    return tuple(int(value[index : index + 2], 16) for index in (1, 3, 5))  # type: ignore[return-value]


def hex_colour(value: tuple[int, int, int]) -> str:
    return "#" + "".join(f"{max(0, min(255, channel)):02X}" for channel in value)


def mix(a: str, b: str, amount: float) -> str:
    ar, ag, ab = rgb(a)
    br, bg, bb = rgb(b)
    return hex_colour(
        (
            round(ar + (br - ar) * amount),
            round(ag + (bg - ag) * amount),
            round(ab + (bb - ab) * amount),
        )
    )


def rgb_csv(value: str) -> str:
    return ",".join(str(channel) for channel in rgb(value))


def derived(data: dict) -> dict[str, str]:
    p = data["palette"]
    return {
        **p,
        "surface_alt": mix(p["sumi"], p["tetsu"], 0.55),
        "accent_soft": mix(p["vermillion"], p["washi"], 0.24),
        "link": mix(p["indigo"], p["washi"], 0.38),
        "positive": mix(p["indigo"], p["washi"], 0.56),
        "warning": mix(p["vermillion"], p["washi"], 0.48),
        "bright": mix(p["washi"], "#FFFFFF", 0.58),
        "dim": mix(p["muted"], p["sumi"], 0.34),
        "violet": mix(p["indigo"], p["vermillion"], 0.46),
    }


def render_design(data: dict) -> str:
    p = data["palette"]
    s = p["semantic"]
    shape = data["shape"]
    spacing = data["spacing"]
    density = data["density"]
    motion = data["motion"]
    wall_utility = resolve_wall_utility(data)
    return f'''// Generated by core/theme.py from ~/.config/cortetsu/ui.toml source.
// Do not hand-edit; run `cortetsu theme compile`.
.pragma library

var colorSumi = "{p['sumi']}"
var colorTetsu = "{p['tetsu']}"
var colorWashi = "{p['washi']}"
var colorIndigo = "{p['indigo']}"
var colorVermillion = "{p['vermillion']}"
var colorMuted = "{p['muted']}"

var colorSurface = colorTetsu
var colorSurfaceHigh = "{s['surface_high']}"
var colorOnSurface = colorWashi
var colorOnSurfaceVariant = colorMuted
var colorPrimary = colorIndigo
var colorOnPrimary = colorWashi
var colorPrimaryContainer = "{s['primary_container']}"
var colorOnPrimaryContainer = colorWashi
var colorSecondary = "{s['secondary']}"
var colorSecondaryContainer = "{s['secondary_container']}"
var colorOnSecondaryContainer = colorWashi
var colorTertiary = colorVermillion
var colorOutline = colorMuted
var colorOutlineVariant = "{s['outline_variant']}"
var colorScrim = "{s['scrim']}"
var colorSurfaceGlass = "{s['surface_glass']}"
var colorSurfaceGlassStrong = "{s['surface_glass_strong']}"
var colorOnSurfaceMuted = "{s['on_surface_muted']}"
var colorSuccess = "{s['success']}"
var colorWarning = "{s['warning']}"

var radiusSmall = {shape['radius_small']}
var radiusMedium = {shape['radius_medium']}
var radiusLarge = {shape['radius_large']}
var radiusSurface = {shape['radius_surface']}
var radiusPill = {shape['radius_pill']}

var spacingUnit = {spacing['unit']}
var spacingCompact = {spacing['compact']}
var spacingStandard = {spacing['standard']}
var spacingComfortable = {spacing['comfortable']}
var spacingSpacious = {spacing['spacious']}
var spacingSection = {spacing['section']}

var overlayOpacity = {density['overlay_opacity']}
var scrimOpacity = {density['scrim_opacity']}
var outlineWidth = {density['outline_width']}
var controlHeight = {density['control_height']}
var rowHeight = {density['row_height']}
var controlHeightPrimary = {density['control_height_primary']}

// Typography aliases keep QML surfaces on the single generated design contract.
var labelSmallPx = 11
var labelMediumPx = 12
var labelLargePx = 14
var bodySmallPx = 12
var bodyPx = 13
var bodyLargePx = 14
var iconSmallPx = 18
var iconMediumPx = 22

var hoverScale = {motion['hover_scale']}
var motionInstantMs = {motion['instant_ms']}
var motionFastMs = {motion['fast_ms']}
var motionStandardMs = {motion['standard_ms']}
var motionDeliberateMs = {motion['deliberate_ms']}
var motionPanelMs = {motion['panel_ms']}

// Wall Utility values resolve symbolic ui.toml references at compile time.
var wallUtilitySurfaceRadius = {wall_utility['surface_radius']}
var wallUtilityPanelMotionMs = {wall_utility['panel_motion']}
var wallUtilityOrbitMotionMs = {wall_utility['orbit_motion']}
var wallUtilityCrossfadeMotionMs = {wall_utility['crossfade_motion']}
var wallUtilityOrbitTopGap = {wall_utility['orbit_top_gap']}
var wallUtilityOrbitBottomGap = {wall_utility['orbit_bottom_gap']}
var wallUtilityFooterGap = {wall_utility['footer_gap']}
var wallUtilityCategoryGap = {wall_utility['category_gap']}
'''


def render_kitty(data: dict) -> str:
    c = derived(data)
    ansi = [
        c["tetsu"],
        c["vermillion"],
        c["positive"],
        c["warning"],
        c["indigo"],
        c["violet"],
        c["link"],
        c["washi"],
        c["muted"],
        c["accent_soft"],
        mix(c["positive"], c["washi"], 0.28),
        mix(c["warning"], c["washi"], 0.28),
        mix(c["indigo"], c["washi"], 0.48),
        mix(c["violet"], c["washi"], 0.34),
        mix(c["link"], c["washi"], 0.38),
        c["bright"],
    ]
    lines = [
        "# Generated by Cortetsu from ui.toml. Do not edit by hand.",
        f"foreground {c['washi']}",
        f"background {c['sumi']}",
        f"selection_foreground {c['washi']}",
        f"selection_background {c['indigo']}",
        f"cursor {c['vermillion']}",
        f"cursor_text_color {c['sumi']}",
        f"url_color {c['link']}",
        f"active_tab_foreground {c['washi']}",
        f"active_tab_background {c['indigo']}",
        f"inactive_tab_foreground {c['muted']}",
        f"inactive_tab_background {c['tetsu']}",
        f"tab_bar_background {c['sumi']}",
    ]
    lines.extend(f"color{index} {value}" for index, value in enumerate(ansi))
    return "\n".join(lines) + "\n"


def render_gtk(data: dict) -> str:
    c = derived(data)
    values = {
        "accent_color": c["vermillion"],
        "accent_fg_color": c["washi"],
        "accent_bg_color": c["vermillion"],
        "window_bg_color": c["sumi"],
        "window_fg_color": c["washi"],
        "headerbar_bg_color": c["tetsu"],
        "headerbar_fg_color": c["washi"],
        "popover_bg_color": c["tetsu"],
        "popover_fg_color": c["washi"],
        "view_bg_color": c["sumi"],
        "view_fg_color": c["washi"],
        "card_bg_color": c["surface_alt"],
        "card_fg_color": c["washi"],
        "theme_bg_color": c["sumi"],
        "theme_fg_color": c["washi"],
        "theme_base_color": c["tetsu"],
        "theme_text_color": c["washi"],
        "theme_selected_bg_color": c["vermillion"],
        "theme_selected_fg_color": c["washi"],
        "insensitive_bg_color": c["tetsu"],
        "insensitive_fg_color": c["muted"],
        "link_color": c["link"],
    }
    lines = ["/* Generated by Cortetsu from ui.toml. Do not edit by hand. */"]
    lines.extend(f"@define-color {name} {value};" for name, value in values.items())
    lines.extend(
        [
            "@define-color primary @accent_color;",
            "@define-color sidebar_bg_color @window_bg_color;",
            "@define-color sidebar_fg_color @window_fg_color;",
            "@define-color sidebar_border_color @card_bg_color;",
            "@define-color sidebar_backdrop_color @window_bg_color;",
        ]
    )
    return "\n".join(lines) + "\n"


def colour_section(name: str, bg: str, alt: str, fg: str, c: dict[str, str]) -> str:
    fields = {
        "BackgroundAlternate": alt,
        "BackgroundNormal": bg,
        "DecorationFocus": c["vermillion"],
        "DecorationHover": c["accent_soft"],
        "ForegroundActive": c["accent_soft"],
        "ForegroundInactive": c["muted"],
        "ForegroundLink": c["link"],
        "ForegroundNegative": c["vermillion"],
        "ForegroundNeutral": c["warning"],
        "ForegroundNormal": fg,
        "ForegroundPositive": c["positive"],
        "ForegroundVisited": c["violet"],
    }
    return "[" + name + "]\n" + "\n".join(f"{key}={rgb_csv(value)}" for key, value in fields.items()) + "\n"


def render_kde(data: dict) -> str:
    c = derived(data)
    sections = [
        "[General]\nColorScheme=Cortetsu\nName=Cortetsu\nTerminalApplication=kitty\n",
        "[KDE]\ncontrast=4\n",
        colour_section("Colors:Button", c["tetsu"], c["surface_alt"], c["washi"], c),
        colour_section("Colors:Complementary", c["sumi"], c["surface_alt"], c["washi"], c),
        colour_section("Colors:Header", c["tetsu"], c["sumi"], c["washi"], c),
        colour_section("Colors:Selection", c["vermillion"], c["accent_soft"], c["washi"], c),
        colour_section("Colors:Tooltip", c["tetsu"], c["surface_alt"], c["washi"], c),
        colour_section("Colors:View", c["sumi"], c["tetsu"], c["washi"], c),
        colour_section("Colors:Window", c["tetsu"], c["surface_alt"], c["washi"], c),
        "[WM]\n"
        f"activeBackground={rgb_csv(c['tetsu'])}\n"
        f"activeBlend={rgb_csv(c['vermillion'])}\n"
        f"activeForeground={rgb_csv(c['washi'])}\n"
        f"inactiveBackground={rgb_csv(c['sumi'])}\n"
        f"inactiveBlend={rgb_csv(c['muted'])}\n"
        f"inactiveForeground={rgb_csv(c['muted'])}\n",
    ]
    return "\n".join(sections)


def outputs(repo: Path, data: dict) -> dict[Path, str]:
    generated = repo / "dotfiles/generated/theme/home/.config"
    return {
        repo / "cortetsu/modules/CortetsuDesign.js": render_design(data),
        generated / "kitty/cortetsu-theme.conf": render_kitty(data),
        generated / "gtk-3.0/cortetsu-colors.css": render_gtk(data),
        generated / "gtk-4.0/cortetsu-colors.css": render_gtk(data),
        generated / "kdeglobals": render_kde(data),
    }


def compile_theme(repo: Path) -> int:
    data = load_ui(repo)
    for path, content in outputs(repo, data).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"GENERATED {path.relative_to(repo)}")
    return 0


def check_theme(repo: Path) -> int:
    data = load_ui(repo)
    stale: list[Path] = []
    for path, expected in outputs(repo, data).items():
        if not path.is_file() or path.read_text(encoding="utf-8") != expected:
            stale.append(path)
    if stale:
        for path in stale:
            print(f"STALE {path.relative_to(repo)}", file=sys.stderr)
        print("ERROR: run `cortetsu theme compile` and commit the generated outputs", file=sys.stderr)
        return 1
    print("PASS: Cortetsu native theme outputs match ui.toml")
    return 0


def adopt_theme_ownership() -> int:
    home = Path.home()
    config_home = Path(os.environ.get("XDG_CONFIG_HOME", home / ".config"))
    data_home = Path(os.environ.get("XDG_DATA_HOME", home / ".local/share"))
    cli = config_home / "caelestia/cli.json"
    if not cli.is_file():
        print(f"Cortetsu theme ownership: no Caelestia CLI config at {cli}; nothing to disable")
        return 0
    try:
        payload = json.loads(cli.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise RuntimeError(f"cannot read {cli}: {exc}") from exc
    if not isinstance(payload, dict):
        raise RuntimeError(f"{cli} does not contain a JSON object")
    theme = payload.setdefault("theme", {})
    if not isinstance(theme, dict):
        raise RuntimeError(f"theme in {cli} is not a JSON object")
    changed = [key for key in THEME_KEYS if theme.get(key) is not False]
    if not changed:
        print("Cortetsu theme ownership: already native for terminal/Hyprland/GTK/Qt")
        return 0

    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    backup = data_home / "cortetsu/migrations" / stamp / "theme-ownership" / "cli.json"
    backup.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(cli, backup)
    for key in THEME_KEYS:
        theme[key] = False
    temp = cli.with_name(cli.name + f".tmp.{os.getpid()}")
    temp.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    os.replace(temp, cli)
    print("Cortetsu theme ownership: disabled Caelestia mutations for terminal/Hyprland/GTK/Qt")
    print(f"BACKUP theme-ownership={backup}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Compile and own the Cortetsu desktop theme")
    parser.add_argument("action", choices=("compile", "check", "adopt"), nargs="?", default="check")
    parser.add_argument("--repo")
    args = parser.parse_args()
    repo = repo_root(args.repo)
    try:
        if args.action == "compile":
            return compile_theme(repo)
        if args.action == "adopt":
            return adopt_theme_ownership()
        return check_theme(repo)
    except (OSError, ValueError, RuntimeError, tomllib.TOMLDecodeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
