// Generated by core/theme.py from ~/.config/cortetsu/ui.toml source.
// Do not hand-edit; run `cortetsu theme compile`.
.pragma library

var colorSumi = "#0B0D10"
var colorTetsu = "#171B21"
var colorWashi = "#E7E0D5"
var colorIndigo = "#334E68"
var colorVermillion = "#D64B32"
var colorMuted = "#8A919B"

var colorSurface = colorTetsu
var colorSurfaceHigh = "#222831"
var colorOnSurface = colorWashi
var colorOnSurfaceVariant = colorMuted
var colorPrimary = colorIndigo
var colorOnPrimary = colorWashi
var colorPrimaryContainer = "#263E53"
var colorOnPrimaryContainer = colorWashi
var colorSecondary = "#526D82"
var colorSecondaryContainer = "#293B4A"
var colorOnSecondaryContainer = colorWashi
var colorTertiary = colorVermillion
var colorOutline = colorMuted
var colorOutlineVariant = "#505862"
var colorScrim = "#000000"
var colorSurfaceGlass = "#1B2028"
var colorSurfaceGlassStrong = "#202731"
var colorOnSurfaceMuted = "#AAB1BA"
var colorSuccess = "#7A9B83"
var colorWarning = "#C49A62"

var radiusSmall = 8
var radiusMedium = 12
var radiusLarge = 20
var radiusSurface = 28
var radiusPill = 999

var spacingUnit = 4
var spacingCompact = 8
var spacingStandard = 12
var spacingComfortable = 16
var spacingSpacious = 24
var spacingSection = 32

var overlayOpacity = 0.94
var scrimOpacity = 0.22
var outlineWidth = 1
var controlHeight = 36
var rowHeight = 52
var controlHeightPrimary = 40

// Typography aliases keep QML surfaces on the single generated design contract.
var labelSmallPx = 11
var labelMediumPx = 12
var labelLargePx = 14
var bodySmallPx = 12
var bodyPx = 13
var bodyLargePx = 14
var iconSmallPx = 18
var iconMediumPx = 22

var hoverScale = 1.025
var motionInstantMs = 80
var motionFastMs = 120
var motionStandardMs = 180
var motionDeliberateMs = 240
var motionPanelMs = 240

// Wall Utility values resolve symbolic ui.toml references at compile time.
var wallUtilitySurfaceRadius = 28
var wallUtilityPanelMotionMs = 240
var wallUtilityOrbitMotionMs = 180
var wallUtilityCrossfadeMotionMs = 180
var wallUtilityOrbitTopGap = 32
var wallUtilityOrbitBottomGap = 32
var wallUtilityFooterGap = 8
var wallUtilityCategoryGap = 8
