// Generated by core/theme.py from ~/.config/cortetsu/ui.toml source.
// Do not hand-edit; run `cortetsu theme compile`.
pragma Singleton

import QtQuick
import "CortetsuDesignDefaults.js" as Defaults

QtObject {
    id: root

    // Role-to-hex map of the active scheme. CortetsuColours owns it; an
    // empty map leaves every token at its ui.toml default.
    property var scheme: ({})

    function role(name, fallback) {
        const value = scheme ? scheme[name] : undefined;
        if (typeof value !== "string")
            return fallback;
        const hex = value.startsWith("#") ? value : `#${value}`;
        return /^#[0-9a-fA-F]{6}$/.test(hex) ? hex : fallback;
    }

    readonly property color colorSumi: role("background", Defaults.colorSumi)
    readonly property color colorTetsu: role("surface", Defaults.colorTetsu)
    readonly property color colorWashi: role("onSurface", Defaults.colorWashi)
    readonly property color colorIndigo: role("primary", Defaults.colorIndigo)
    readonly property color colorVermillion: Defaults.colorVermillion
    readonly property color colorMuted: Defaults.colorMuted
    readonly property color colorSurface: colorTetsu
    readonly property color colorSurfaceHigh: role("surfaceContainerHigh", Defaults.colorSurfaceHigh)
    readonly property color colorOnSurface: colorWashi
    readonly property color colorOnSurfaceVariant: role("onSurfaceVariant", Defaults.colorOnSurfaceVariant)
    readonly property color colorPrimary: role("primary", Defaults.colorPrimary)
    readonly property color colorOnPrimary: role("onPrimary", Defaults.colorOnPrimary)
    readonly property color colorPrimaryContainer: role("primaryContainer", Defaults.colorPrimaryContainer)
    readonly property color colorOnPrimaryContainer: role("onPrimaryContainer", Defaults.colorOnPrimaryContainer)
    readonly property color colorSecondary: role("secondary", Defaults.colorSecondary)
    readonly property color colorSecondaryContainer: role("secondaryContainer", Defaults.colorSecondaryContainer)
    readonly property color colorOnSecondaryContainer: role("onSecondaryContainer", Defaults.colorOnSecondaryContainer)
    readonly property color colorTertiary: role("tertiary", Defaults.colorTertiary)
    readonly property color colorOutline: role("outline", Defaults.colorOutline)
    readonly property color colorOutlineVariant: role("outlineVariant", Defaults.colorOutlineVariant)
    readonly property color colorScrim: Defaults.colorScrim
    readonly property color colorSurfaceGlass: role("surfaceContainer", Defaults.colorSurfaceGlass)
    readonly property color colorSurfaceGlassStrong: role("surfaceContainerHigh", Defaults.colorSurfaceGlassStrong)
    readonly property color colorOnSurfaceMuted: Defaults.colorOnSurfaceMuted
    readonly property color colorSuccess: role("success", Defaults.colorSuccess)
    readonly property color colorWarning: Defaults.colorWarning
    readonly property real radiusSmall: Defaults.radiusSmall
    readonly property real radiusMedium: Defaults.radiusMedium
    readonly property real radiusLarge: Defaults.radiusLarge
    readonly property real radiusSurface: Defaults.radiusSurface
    readonly property real radiusPill: Defaults.radiusPill
    readonly property real spacingUnit: Defaults.spacingUnit
    readonly property real spacingCompact: Defaults.spacingCompact
    readonly property real spacingStandard: Defaults.spacingStandard
    readonly property real spacingComfortable: Defaults.spacingComfortable
    readonly property real spacingSpacious: Defaults.spacingSpacious
    readonly property real spacingSection: Defaults.spacingSection
    readonly property real bottomHubHeight: Defaults.bottomHubHeight
    readonly property real overlayOpacity: Defaults.overlayOpacity
    readonly property real scrimOpacity: Defaults.scrimOpacity
    readonly property real outlineWidth: Defaults.outlineWidth
    readonly property real controlHeight: Defaults.controlHeight
    readonly property real rowHeight: Defaults.rowHeight
    readonly property real controlHeightPrimary: Defaults.controlHeightPrimary
    readonly property real labelSmallPx: Defaults.labelSmallPx
    readonly property real labelMediumPx: Defaults.labelMediumPx
    readonly property real labelLargePx: Defaults.labelLargePx
    readonly property real bodySmallPx: Defaults.bodySmallPx
    readonly property real bodyPx: Defaults.bodyPx
    readonly property real bodyLargePx: Defaults.bodyLargePx
    readonly property real iconSmallPx: Defaults.iconSmallPx
    readonly property real iconMediumPx: Defaults.iconMediumPx
    readonly property real hoverScale: Defaults.hoverScale
    readonly property real motionInstantMs: Defaults.motionInstantMs
    readonly property real motionFastMs: Defaults.motionFastMs
    readonly property real motionStandardMs: Defaults.motionStandardMs
    readonly property real motionDeliberateMs: Defaults.motionDeliberateMs
    readonly property real motionPanelMs: Defaults.motionPanelMs
    readonly property real wallUtilitySurfaceRadius: Defaults.wallUtilitySurfaceRadius
    readonly property real wallUtilityPanelMotionMs: Defaults.wallUtilityPanelMotionMs
    readonly property real wallUtilityOrbitMotionMs: Defaults.wallUtilityOrbitMotionMs
    readonly property real wallUtilityCrossfadeMotionMs: Defaults.wallUtilityCrossfadeMotionMs
    readonly property real wallUtilityOrbitTopGap: Defaults.wallUtilityOrbitTopGap
    readonly property real wallUtilityOrbitBottomGap: Defaults.wallUtilityOrbitBottomGap
    readonly property real wallUtilityFooterGap: Defaults.wallUtilityFooterGap
    readonly property real wallUtilityCategoryGap: Defaults.wallUtilityCategoryGap
}
